config/routes.rb
Rails.application.routes.draw do
  #get 'home/zipcode'
  root 'home#index'
  post "zipcode"=>'home#zipcode'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    @url ='http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=20002&distance=25&API_KEY=6C05FE7C-2BEA-4C0C-864E-9A739030C0D6'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output=JSON.parse(@response)

    #Check for empty return result

    if @output.empty? || !@output
      @final_output = 'Error'
    else
      @final_output = @output[0]['AQI']
    end

     if @final_output == 'Error'
      @api_color ="silver"
     elsif @final_output.to_i <=50
      @api_color ='green'
      @api_description='AQI: Good (0 - 50)
Air quality is considered satisfactory, and air pollution poses little or no risk.'
     elsif @final_output.to_i>=51 && @final_output.to_i<=100
      @api_color="yellow"
      @api_description='AQI: Moderate (51 - 100)
Air quality is acceptable; however, for some pollutants there may be a moderate health concern for a very small number of people who are unusually sensitive to air pollution'
     elsif @final_output.to_i>=101 && @final_output.to_i<=150
      @api_color="orange"
      @api_description='AQI: Unhealthy for Sensitive Groups (101 - 150)
Although general public is not likely to be affected at this AQI range, people with lung disease, older adults and children are at a greater risk from exposure to ozone, whereas persons with heart and lung disease, older adults and children are at greater risk from the presence of particles in the air.'
     elsif @final_output.to_i>=151 && @final_output.to_i<=200
      @api_color ="red"
      @api_description='AQI: Unhealthy (151 - 200)
Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects.'
     elsif @final_output.to_i>=201 && @final_output.to_i<=300
      @api_color="purle"
      @api_description='AQI: Very Unhealthy (201 - 300)
Health alert: everyone may experience more serious health effects.'
     elsif @final_output.to_i>=301 && @final_output.to_i<=500
      @api_color='maroon' 
      @api_description='AQI: Hazardous (301 - 500)
Health warnings of emergency conditions. The entire population is more likely to be affected.'
     end
  end

  def zipcode
    @zip_query = params[:zipcode]

    if params[:zipcode] == ""
      @zip_query ="Hey you forgot to enter a zipcode!"
    else
      #Do API stuff


    require 'net/http'
    require 'json'
    @url ='http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query+ '&distance=25&API_KEY=6C05FE7C-2BEA-4C0C-864E-9A739030C0D6'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output=JSON.parse(@response)

    #Check for empty return result

    if @output.empty? || !@output
      @final_output = 'Error'
    else
      @final_output = @output[0]['AQI']
    end

     if @final_output == 'Error'
      @api_color ="silver"
     elsif @final_output<=50
      @api_color ='green'
      @api_description='AQI: Good (0 - 50)
Air quality is considered satisfactory, and air pollution poses little or no risk.'
     elsif @final_output>=51 && @final_output<=100
      @api_color="yellow"
      @api_description='AQI: Moderate (51 - 100)
Air quality is acceptable; however, for some pollutants there may be a moderate health concern for a very small number of people who are unusually sensitive to air pollution'
     elsif @final_output>=101 && @final_output<=150
      @api_color="orange"
      @api_description='AQI: Unhealthy for Sensitive Groups (101 - 150)
Although general public is not likely to be affected at this AQI range, people with lung disease, older adults and children are at a greater risk from exposure to ozone, whereas persons with heart and lung disease, older adults and children are at greater risk from the presence of particles in the air.'
     elsif @final_output>=151 && @final_output<=200
      @api_color ="red"
      @api_description='AQI: Unhealthy (151 - 200)
Everyone may begin to experience health effects; members of sensitive groups may experience more serious health effects.'
     elsif @final_output>=201 && @final_output<=300
      @api_color="purle"
      @api_description='AQI: Very Unhealthy (201 - 300)
Health alert: everyone may experience more serious health effects.'
     elsif @final_output>=301 && @final_output<=500
      @api_color='maroon' 
      @api_description='AQI: Hazardous (301 - 500)
Health warnings of emergency conditions. The entire population is more likely to be affected.'
     end

    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'My Ozone',root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <%= form_tag zipcode_path, :method=>'POST' do %>
      <div class='form-inline my-2 my-lg-0'>
        <%= text_field_tag 'zipcode',nil,placeholder: 'Search Zipcode',clas: "form-control mr-sm-2" %>
        <%= submit_tag 'Search', class: 'btn btn-outline-secondary my-2 my-sm-0' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4>"><%= @final_output%></h1>
  <p class="lead">This is the current ozone air quality readout for USA areas ...</p>
  <hr class="my-4">
  <%= @api_description %>
  <br/>
</div>
<br/>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4>"><%= @final_output%></h1>
  <p class="lead">This is the current ozone air quality readout for the <%= @zip_query %> zipcode.</p>
  <hr class="my-4">
  <%= @api_description %>
  <br/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/navbar' %>
    <div class='container'>
      <br/>
      <%= yield %>
    </div>
  </body>
</html>